language: R
cache: packages

r: devel
r: release
r: oldrel
r: 3.4
r: 3.3

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: change
