language: R
cache: packages

r:
  - devel
  - release
  - oldrel
  - 3.5
  - 3.4

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: change
